### ISSUE TITLE
includedir / sysincludedir incorrectly set for XCode

### ISSUE THREAD

**Issue by soundsrc** [premake/premake-xcode#24]
According to the premake docs:
https://github.com/premake/premake-core/wiki/sysincludedirs
sysincludedir maps to the -isystem flags in GCC/Clang, whereas includedir maps to the -I command.

The current xcode generator maps "sysincludedir" to the Xcode's HEADER_SEARCH_PATH (clang's -I flag),  and "includedir" to XCode's USER_HEADER_SEARCH_PATHS (clang's -iquote flag).

This causes all headers with angled brackets, ie. #include &lt;SomeHeader.h&gt; to be not recognized on the search path when specified with the "includedir" option in premake5.

I think that "includedir" should be mapped to "HEADER_SEARCH_PATH" which is the equivalent of -I option of gcc/clang and this is the same behaviour in premake4. As for "sysincludedir", I'm not sure if there is a XCode equivalent, perhaps it should be mapped to the same thing.

https://github.com/soundsrc/premake-xcode/tree/include-dir-fix

**Comment by starkos** [comment]
Since it sounds like you already have a fix, can you submit a pull request with the changes?

**Comment by soundsrc** [comment]
Yep. Just wanted to make sure. Sent.

**Comment by fzwoch** [comment]
I fell into this pitfall once as well. Can we get premake/premake-xcode#26 merged?

**Comment by starkos** [comment]
Merged.
